# Generated by Django 2.2.6 on 2019-11-16 03:20

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='products/'),
        ),
    ]
