# Generated by Django 2.2.6 on 2019-11-26 19:39

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191117_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carouselImage',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='carousel'),
        ),
    ]
