# Generated by Django 2.2.6 on 2019-11-26 19:42

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImageHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouselImage', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='carouselImage')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='carouselImage',
        ),
    ]
