# Generated by Django 2.2.6 on 2019-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191126_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimagehome',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
