# Generated by Django 2.2.6 on 2019-11-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_carouselimagehome_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimagehome',
            old_name='active',
            new_name='use',
        ),
    ]
