# Generated by Django 2.2.6 on 2019-11-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191126_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimagehome',
            options={},
        ),
        migrations.AlterModelTable(
            name='carouselimagehome',
            table=None,
        ),
    ]
