# Generated by Django 2.2.6 on 2019-11-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191126_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimagehome',
            options={'verbose_name': 'Imagens do carousel'},
        ),
        migrations.AlterModelTable(
            name='carouselimagehome',
            table='CarouselImage',
        ),
    ]
