# Generated by Django 2.2.6 on 2019-11-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191126_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImageHome',
        ),
    ]
