# Generated by Django 2.2.6 on 2019-11-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_carouselimagehome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
